language: python
python:
    - "3.8"

# install dependencies
install:
    - make install

# run tests
script:
    - make tests

# upload code coverage
after_success:
    - bash <(curl -s https://codecov.io/bash)
